engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
    exclude_paths:
      - "migrations/"
      - "test/**/*-test.js"
  eslint:
    enabled: true
  fixme:
    enabled: true
  # nodesecurity:
  #   enabled: true
  scss-lint:
    enabled: true
ratings:
   paths:
     - "**.js"
     - "**.scss"
