exclude_paths:
  - "semantic/" # Generated files
  - "src/styles/" # These are compiled
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
    exclude_paths:
      - "test/**/*.test.js"
      - "config/webpack.config.*.js"
  eslint:
    enabled: true
  fixme:
    enabled: true
  # nodesecurity:
  #   enabled: true
  scss-lint:
    enabled: true
ratings:
   paths:
     - "**.js"
     - "**.scss"
